# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-18 12:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planning',
            old_name='type',
            new_name='publication',
        ),
    ]
