# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-21 06:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_planning_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HeadDepartment',
            fields=[
                ('head_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ITA_Employee',
            fields=[
                ('ita_employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=100)),
                ('funktion', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255)),
                ('status', models.CharField(max_length=100)),
                ('department', models.ForeignKey(db_column='department_id', on_delete=django.db.models.deletion.CASCADE, to='project.Department')),
            ],
        ),
        migrations.CreateModel(
            name='PaperEmployee',
            fields=[
                ('paper_employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('factor', models.IntegerField()),
                ('paper_id', models.ForeignKey(db_column='planning_id', on_delete=django.db.models.deletion.CASCADE, to='project.Planning')),
            ],
        ),
        migrations.CreateModel(
            name='PublicationEmployee_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('emp_status_id', models.ForeignKey(db_column='paper_employee_id', on_delete=django.db.models.deletion.CASCADE, to='project.PaperEmployee')),
            ],
        ),
        migrations.CreateModel(
            name='StudyField',
            fields=[
                ('study_id', models.AutoField(primary_key=True, serialize=False)),
                ('study_field', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='headdepartment',
            name='study_field',
            field=models.ForeignKey(db_column='study_id', on_delete=django.db.models.deletion.CASCADE, to='project.StudyField'),
        ),
        migrations.AddField(
            model_name='department',
            name='head_department',
            field=models.ForeignKey(db_column='head_id', on_delete=django.db.models.deletion.CASCADE, to='project.HeadDepartment'),
        ),
    ]
